### ISSUE TITLE
Cannot install previous version of yarn using apt-get/apt-cache

### ISSUE THREAD

**Issue by MoOx** [yarnpkg/yarn#1839]
**Do you want to request a *feature* or report a *bug*?**

Bug?

**What is the current behavior?**

If I list all existing version of yarn using `apt-get policy`, I only see latest version

**If the current behavior is a bug, please provide the steps to reproduce.**

```
  # Repo for newer Node.js versions
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  # trying 0.16.1 because https://github.com/yarnpkg/yarn/issues/1838
  - sudo apt-cache policy yarn
yarn:
  Installed: (none)
  Candidate: 0.17.0-1
  Version table:
     0.17.0-1 0
        500 http://dl.yarnpkg.com/debian/ stable/main amd64 Packages
```

**What is the expected behavior?**

I would expect to see 0.16.1-1.

Note: I am not a comfortable with apt-get/apt-cache so maybe I am doing something wrong, but find on the net that apt-cache policy command should give all available version.

**Please mention your node.js, yarn and operating system version.**

$ node --version

v6.9.1

$ npm --version

3.10.8

$ nvm --version

0.32.0

yarn 0.17.0
