### ISSUE TITLE
Yarn forces install to node_modules when adding new dependencies

### ISSUE THREAD

**Issue by enjikaka** [yarnpkg/yarn#2755]
**What is the current behavior?**

`yarn add --dev <package>` installs all dependencies to node_modules

**If the current behavior is a bug, please provide the steps to reproduce.**

- `rm -rf node_modules/`
- `yarn add --dev <package>`
- node_modules created and filled up

**What is the expected behavior?**

**Should be able to add dependencies without installing them.** For usage with docker where you want the dependencies in the docker container. Today I have to wait an eternity after adding a dep, only to remove node_modules/ after the yarn command finishes; and then run the dev docker image which installs, _only_, the new dependency.

**Comment by enjikaka** [comment]
Dockerfile (based on https://hackernoon.com/using-yarn-with-docker-c116ad289d56#.vmx4jd31k )

```
FROM node:6-alpine

RUN mkdir -p /opt

RUN apk update
RUN apk add git
RUN apk add --no-cache --virtual .build-deps make gcc g++ python ca-certificates wget
RUN update-ca-certificates

# Install yarn
RUN wget -O /opt/latest.tar.gz https://yarnpkg.com/latest.tar.gz
RUN tar -C /opt -zxvf /opt/latest.tar.gz
RUN mv /opt/dist /opt/yarn
ENV PATH "$PATH:/opt/yarn/bin"

ADD package.json yarn.lock /tmp/

# Copy cache contents (if any) from local machine
ADD .yarn-cache.tgz /

# Install packages using Yarn
# (trick to make use of Docker layer
# caching to avoid to reinstall all
# modules each time you build the container.)
# Yarn is executed only when you change package.json
# (and the first time, of course).
RUN cd /tmp && yarn
RUN mkdir -p /opt/app && cd /opt/app && ln -s /tmp/node_modules

# Clean build stuff not needed on runtime
RUN rm -rf /opt/yarn
RUN rm /opt/latest.tar.gz
RUN apk del .build-deps

WORKDIR /opt/app
```

docker-compose.yml
```
version: '2'

services:
  app:
    build: .
    image: project/dev-image
    working_dir: /opt/app
    container_name: "dev"
    volumes:
      - "./:/opt/app"
      - /opt/app/node_modules
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=development
      - PORT=8081
    command: npm run dev
```
