### ISSUE TITLE
TravisCI sometimes fails to install yarn via curl + `install.sh`

### ISSUE THREAD

**Issue by eventualbuddha** [yarnpkg/yarn#3600]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
TravisCI builds sometimes fail to install yarn.

**If the current behavior is a bug, please provide the steps to reproduce.**
This is not reliable behavior, but I've seen several TravisCI builds fail because of what appears to be a problem with yarnpkg.com. See [this](https://travis-ci.org/decaffeinate/decaffeinate-parser/jobs/240457699) and [this](https://travis-ci.org/decaffeinate/decaffeinate-parser/jobs/240457700) for two examples.

**What is the expected behavior?**
`curl -o- -L https://yarnpkg.com/install.sh | bash` should properly install yarn by having the server respond with a bash script rather than an HTML page.

**Please mention your node.js, yarn and operating system version.**
This problem comes about before node.js or yarn come into play. The operating system is `2.15-0ubuntu10.18` but I doubt that matters.

**Comment by Daniel15** [comment]
Both build jobs that you linked to show up as successful builds for me. Could you please include the raw build logs?

**Comment by eventualbuddha** [comment]
Looks like there's no way to get the logs for a previous run of a build (I ran re-build to get it to pass). I can tell you that the first line of the output that bash choked on was `<!DOCTYPE…` (ellipsis indicating I don't remember after that). I think curl may have indicated a 500 response, but that I'm less sure of. If I see it again I'll post here.

**Comment by artf** [comment]
I think I got the same error, here is the interested part
```sh
Installing yarn
0.08s$ curl -o- -L https://yarnpkg.com/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5684    0  5684    0     0  91758      0 --:--:-- --:--:-- --:--:--  102k
bash: line 1: syntax error near unexpected token `newline'
bash: line 1: `<!DOCTYPE html>'
The command "curl -o- -L https://yarnpkg.com/install.sh | bash" failed and exited with 2 during .
Your build has been stopped.
```
Using this config
```js
{
  "language": "node_js",
  "node_js": "7.6",
  "group": "stable",
  "dist": "precise",
  "os": "linux"
}
```

**Comment by eventualbuddha** [comment]
@artf yep, that's what I saw. Thanks for capturing it!

**Comment by BYK** [comment]
I think this was a transient issue so closing.

**Comment by kristfal** [comment]
This issue is back. We're seeing it on our BitbucketPipelines CI. 

Our config is:

```
pipelines:
  default:
    - step:
        name: Build
        image: node:8
        caches:
          - yarncustom
        script:
          - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
          - export PATH=$HOME/.yarn/bin:$PATH
          - yarn
          - yarn test
definitions:
  caches:
    yarncustom: /usr/local/share/.cache/yarn/v1
```
