### ISSUE TITLE
Yarn scripts wont run in

### ISSUE THREAD

**Issue by jdelibas** [yarnpkg/yarn#6363]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, yarn and operating system version.**

**Comment by hanxue** [comment]
As a workaround, try setting the cache folder in your `Dockerfile` to 

```bash
YARN_CACHE_FOLDER=/dev/shm/yarn_cache yarn --production
```
or temporarily reset the `HOME` directory

```bash
HOME=$(pwd) yarn install
```

**Comment by anshupitlia** [comment]
Has this been fixed? 

I tried this:
```
RUN mkdir -p /somefolder
YARN_CACHE_FOLDER=/somefolder yarn --production
```

It didn't work for me.

**Comment by zwbetz-gh** [comment]
I fixed this by adding a step at the top to make the dir then recursively `chown` it. 

Replace `someuser` with whatever user you're using in your `Dockerfile`

```
RUN mkdir -p /home/someuser && chown -R someuser:someuser /home/someuser
```

**Comment by kkalavantavanich** [comment]
@zwbetz-gh I don't think that'll work for the OP due to this option:
```
readOnlyRootFilesystem: true  
```

**Comment by alitoufighi** [comment]
I have the same issue as described here: https://stackoverflow.com/questions/66736395/readonly-cache-for-yarn-in-docker
Ignoring writing to cache in case of read-only errors can solve it for me.

**Comment by pulpdood** [comment]
In my case, I found that my Docker was running out of space and I had to increase disk size.

**Comment by spacecowboy** [comment]
This is what I did to get something using yarn to run on a readonlyfilesystem (using the node base image)

In kubernetes:

```
[...]
    spec:
      volumes:
        - name: tmp1
          emptyDir:
            medium: Memory
        - name: tmp2
          emptyDir:
            medium: Memory
        - name: tmp3
          emptyDir:
            medium: Memory
[...]
      containers:
        - name: my-yarn-thingy
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            privileged: false
            runAsNonRoot: true
          volumeMounts:
            - name: tmp1
              mountPath: /tmp
            - name: tmp2
              mountPath: /home/node/.yarn
            - name: tmp3
              mountPath: /home/node/.cache
[...]
```
