### ISSUE TITLE
Make `yarn install --ignore-scripts` more specific

### ISSUE THREAD

**Issue by ryandrew14** [yarnpkg/yarn#7338]
**Do you want to request a *feature* or report a *bug*?**

I would like to request a feature.

**What is the current behavior?**
`yarn install --ignore-scripts` ignores all scripts, including the postinstall script of your project and those of your project's dependencies.

**What is the desired behavior?**
`yarn install --ignore-scripts` has options to ignore either your local postinstall script (my use case), or your dependencies' postinstall scripts (mentioned in #5450). This might work best if you can specify exactly what scripts to ignore, with something like a `--ignore-scripts=local,node-sass` option to ignore specific scripts.

**Please mention your node.js, yarn and operating system version.**
Node 10.16.0, Yarn 1.16.0, Mac OSX Mojave

**Comment by Vadorequest** [comment]
Would be useful with GitHub Actions, as recommended by https://github.com/actions/setup-node#usage

```
steps:
- uses: actions/checkout@v1
- uses: actions/setup-node@v1
  with:
    node-version: '10.x'
    registry-url: 'https://registry.npmjs.org'
# Skip post-install scripts here, as a malicious
# script could steal NODE_AUTH_TOKEN.
- run: npm install --ignore-scripts
  env:
    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
# `npm rebuild` will run all those post-install scripts for us.
- run: npm rebuild && npm run prepare --if-present
```
