### ISSUE TITLE
yarn2 lock file added @npm in the package name in yarnk.lock file

### ISSUE THREAD

**Issue by sangharshcs** [yarnpkg/yarn#8608]
with package.json 
```
  "devDependencies": {
    "@redocly/openapi-cli": "^1.0.0-beta.31",
}
```

Entry in yarn.lock

```
"@redocly/openapi-cli@npm:^1.0.0-beta.31":
  version: 1.0.0-beta.31
  resolution: "@redocly/openapi-cli@npm:1.0.0-beta.31"
  dependencies:
    "@redocly/openapi-core": ^1.0.0-beta.31
    "@types/node": ^14.11.8
    assert-node-version: ^1.0.3
    chokidar: ^3.4.0
    colorette: ^1.2.0
    glob: ^7.1.6
    glob-promise: ^3.4.0
    handlebars: ^4.7.6
    portfinder: ^1.0.26
    readline: ^1.3.0
    simple-websocket: ^9.0.0
    yargs: ^15.3.1
  bin:
    openapi: bin/cli.js
  checksum: bb74c6fa7c87e9f31e8160bb78f64fb9121913a681ec617762712ec8c11ede162c4130f9321beaffa0e3c2cc7399b2235518fd354dcbac1f4853847ac5a5ea08
  languageName: node
  linkType: hard
```

Any idea why additional @npm in the yarn.lock entry i.e. "@redocly/openapi-cli@npm:^1.0.0-beta.31"? Any workaround to avoid it. I have generated yarn.lock with yarn v1 and @npm was not there.
