### ISSUE TITLE
Using PAT to access private repository

### ISSUE THREAD

**Issue by Ciloe** [yarnpkg/yarn#9049]
Hi there !

I tried to connect to a private repository with yarn. I added this line : 

package.json
```json
"dependencies": {
  "wtd-tsx": "git+https://<TOKEN>:x-oauth-basic@github.com/<owner>/<repo>.git#main"
}
```

But I have this error in github action : 
<img width="1394" alt="Capture d’écran 2024-04-09 à 11 26 21" src="https://github.com/yarnpkg/yarn/assets/1830492/2f34e814-6940-4e06-ae0a-332f20bf8cb9">

I tried to do some other things : 

.yarnrc
```
"@repeaterstore:wtd-tsx" "https://npm.pkg.github.com"
```

Or add PAT in secrets in the workflow

```yaml
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - uses: actions/setup-node@v4.0.2
        with:
          node-version: '18'

      - name: Install for CI
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT }}
        run: yarn
```

This is the PAT config : 
<img width="804" alt="Capture d’écran 2024-04-09 à 11 31 26" src="https://github.com/yarnpkg/yarn/assets/1830492/2ca6b9bd-f25a-4fab-b2a4-7969be553b18">
